[platformio]
src_dir = main

[env:c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = espidf
board_build.spiffs_embed_files = data
monitor_speed = 115200
board_build.partitions = partitions.c3.csv
board_build.filesystem = spiffs
build_type = release
