[platformio]
src_dir = main

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = espidf
board_build.spiffs_embed_files = data
monitor_speed = 115200
board_build.filesystem = spiffs
build_type = release
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.${PIOENV}"
board_build.esp-idf.sdkconfig_path = sdkconfig

[env:esp32c3]
board = esp32-c3-devkitm-1
board_build.partitions = partitions.c3.csv
